### PR TITLE
Add csv missing files

### PR DESCRIPTION
**Pull request by Marie59**
Hi @cfrat74 and @geofrizz after trying some things with conda and talking with conda admin they seem to think that the csv files are not present in the conda package because they are not present in the setup.py of the package. 
Here I did a modification to change that but I never wrote any setup.py in my life. Do you think it's good like that ?

### CODE REVIEW

**Comment by geofrizz** [comment]
Hi @Marie59 and @cfrat74 
In the branch PAOLO I modified the file setup.py, I added the explicit command 'include' for include also the csv files.
Probably 'conda' filter all the file that aren't python code.
I tested in a docker images (docker/Dockerfile_source_test) ... for me it works, I can import the 'SOURCE' module in the python shell.
We wait for some good news (we hope !!) :-)

**Comment by Marie59** [comment]
> Hi @Marie59 and @cfrat74 In the branch PAOLO I modified the file setup.py, I added the explicit command 'include' for include also the csv files. Probably 'conda' filter all the file that aren't python code. I tested in a docker images (docker/Dockerfile_source_test) ... for me it works, I can import the 'SOURCE' module in the python shell. We wait for some good news (we hope !!) :-)

Hi ! Great news !! Do you think your PAOLO branch is ready and can be merged with the master one ? That way I can directly do a new version of source and it will directly update the conda package

**Comment by geofrizz** [comment]
Well, In my branch I tested the code for create some docker images (standalone, with jupyter and with galaxy-jupyter) but in every Dockerfile* I used the 'copy' command  and not the 'setup.py install' for add the SOURCE module.

Probably, for the moment, the only one file useful for the main branch is the file 'setup.py'.

Let me to adapt also the Dockerfile* with the use of the setup file ...

Now inside a INGV we have a server for development in which I try to install different docker images of galaxy (I need to use a docker version of galaxy, for maintain the server clean) some are very old or use other old docker images; currently I 'dockerized' the usegalaxy-eu but I need to read more documentation for a correct configuration, for test my galaxy-jupyter-source image.

**Comment by Marie59** [comment]
Ok no problem I will just bring the setup.py in the master branch and leave your PR open. That way you can kep on adding you changes on the docker images there :) Thanks for your work @geofrizz

**Comment by geofrizz** [comment]
Hi @Marie59 ,
today I worked for generalize the import of files with an extension different from '.py';
I modified the 'setup.py' file and added the 'MANIFEST.in'.
In the file MANIFEST.in I inserted only a row: 'recursive-include SOURCE *.py *.csv *.txt'

**Comment by Marie59** [comment]
Okay I will change the master branch and see if those changes works for conda

**Comment by Marie59** [comment]
@geofrizz Great news !! Source on conda should now be working with the csv files ! Thanks a lot !!

**Pull request merged**
